export const ytCookies = [
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701697,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-1PAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "vaWvxcSGHQYXU363/AYnvPXdCz_O2I2ZAZ",
    id: 1,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701939,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a0000QhCVklRk7FUcMaOqP1iSmut0Km9BZc0DGnwZxYJMXu_WQaroN61OlLRauy6qg7peOMRbAACgYKAYMSARUSFQHGX2MixLn5u0wkssfn9Uphx5P3ERoVAUF8yKqyKvnuSpEL2X9-vMqpiYTG0076",
    id: 2,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787642943.42077,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzX-0PQdQ6uL_-xZruEhqf21M5RVUtFGflU0ZhBsngZT7ThoPD3Mh9VJs_u1ajcj-Pdcqw",
    id: 3,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787642784.872572,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-1PSIDTS",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjIB5H03Px6jsh66x8pDBkKlOIlTk_axgHodjcP435g8PR7wRpQG9vGFMzoE0WEhfACWhxAA",
    id: 4,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701724,
    hostOnly: false,
    httpOnly: false,
    name: "__Secure-3PAPISID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value: "vaWvxcSGHQYXU363/AYnvPXdCz_O2I2ZAZ",
    id: 5,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701966,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSID",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "g.a0000QhCVklRk7FUcMaOqP1iSmut0Km9BZc0DGnwZxYJMXu_WQarEvxyD03J1in77T4X2VPofgACgYKAeUSARUSFQHGX2MizQz7_EIIBTvAkOEdCdD1sxoVAUF8yKrfdKdVxXpvxOzn3fVo-Cqt0076",
    id: 6,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787642943.420816,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDCC",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AKEyXzXX6Ybu0sOUBaCvdevV3W9oYieY9k3f0zu9iH4poKRzm6ISf_FLjsYAMOvmg0TpBE77rw",
    id: 7,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787642784.872673,
    hostOnly: false,
    httpOnly: true,
    name: "__Secure-3PSIDTS",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "sidts-CjIB5H03Px6jsh66x8pDBkKlOIlTk_axgHodjcP435g8PR7wRpQG9vGFMzoE0WEhfACWhxAA",
    id: 8,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701641,
    hostOnly: false,
    httpOnly: false,
    name: "APISID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "LJgw_hywqJjDeAEv/ABJYIWm3x_-r37HnL",
    id: 9,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787251383.760679,
    hostOnly: false,
    httpOnly: true,
    name: "GOOGLE_LOGIN",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "sebastian.fals.lopez@gmail.com",
    id: 10,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701536,
    hostOnly: false,
    httpOnly: true,
    name: "HSID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value: "Ag5AXzNHAQ9TGEXxp",
    id: 11,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787253478.314552,
    hostOnly: false,
    httpOnly: true,
    name: "LOGIN_INFO",
    path: "/",
    sameSite: "no_restriction",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "AFmmF2swRAIgS4PTMJGAjeTkJv1-TrVoMV-Ol5_Kx3cJdVIcOERecvACIG6A5TXw-bS6QNNDhMdSQKYgppbzc0oRTkLM0ax8FNVW:QUQ3MjNmd2xGWms5MWpldk9zVXdEaHRtbTF1R2pfSDlUZGJldDNRUWRfVExSU3lweUxiTEdYUmREVmk5blA1Ri16cURVRTBrdWhqaU5oNnExSGJwbTloQ1phcHlVNEN1ZVAtUUhZYnI4c2RuZm03M25NeWN3QkxoWTQ2MmJmM05mZFB2X2dXSjdGdDNmRmExWnoxX0gxcnZhWDkwRTRXR1ln",
    id: 12,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1790666922.889613,
    hostOnly: false,
    httpOnly: false,
    name: "PREF",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value:
      "f6=40000080&f7=100&tz=America.Bogota&repeat=NONE&f4=4000000&autoplay=true",
    id: 13,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701671,
    hostOnly: false,
    httpOnly: false,
    name: "SAPISID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "vaWvxcSGHQYXU363/AYnvPXdCz_O2I2ZAZ",
    id: 14,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.70191,
    hostOnly: false,
    httpOnly: false,
    name: "SID",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "g.a0000QhCVklRk7FUcMaOqP1iSmut0Km9BZc0DGnwZxYJMXu_WQariFEI7NavkqDxoEZSOkhr3gACgYKAWwSARUSFQHGX2MiF2ZC7hsxL8ivevy6J9U6ExoVAUF8yKrmXkxAOnvjM-5Xi8O3MHGU0076",
    id: 15,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1787642943.420684,
    hostOnly: false,
    httpOnly: false,
    name: "SIDCC",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "AKEyXzVLzU_32Hxs3kEO-hZz7pB8qnylaZagkyvOj9JrzaCLS303mgJOrCdBHaiOpGU5tRHp9A",
    id: 16,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1789859903.701611,
    hostOnly: false,
    httpOnly: true,
    name: "SSID",
    path: "/",
    sameSite: "unspecified",
    secure: true,
    session: false,
    storeId: "0",
    value: "AsQo0CXJn4_qqjir8",
    id: 17,
  },
  {
    domain: ".youtube.com",
    expirationDate: 1756106948,
    hostOnly: false,
    httpOnly: false,
    name: "ST-3opvp5",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: false,
    storeId: "0",
    value:
      "session_logininfo=AFmmF2swRAIgS4PTMJGAjeTkJv1-TrVoMV-Ol5_Kx3cJdVIcOERecvACIG6A5TXw-bS6QNNDhMdSQKYgppbzc0oRTkLM0ax8FNVW%3AQUQ3MjNmd2xGWms5MWpldk9zVXdEaHRtbTF1R2pfSDlUZGJldDNRUWRfVExSU3lweUxiTEdYUmREVmk5blA1Ri16cURVRTBrdWhqaU5oNnExSGJwbTloQ1phcHlVNEN1ZVAtUUhZYnI4c2RuZm03M25NeWN3QkxoWTQ2MmJmM05mZFB2X2dXSjdGdDNmRmExWnoxX0gxcnZhWDkwRTRXR1ln",
    id: 18,
  },
  {
    domain: ".youtube.com",
    hostOnly: false,
    httpOnly: false,
    name: "wide",
    path: "/",
    sameSite: "unspecified",
    secure: false,
    session: true,
    storeId: "0",
    value: "0",
    id: 19,
  },
];
